name: PR Agent Training

on:
  pull_request:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run RL training script
        env:
          PYTHONPATH: ${{ github.workspace }}
        working-directory: ${{ github.workspace }}
        run: python -m rl.rl_autopr