name: Train and AutoPR Agent on PR

on:
  pull_request:
    branches: [main]

jobs:
  autopr:
    runs-on: ubuntu-latest

    env:
      GH_PAT: ${{ secrets.GH_PAT }}
      REPO_NAME: your-username/your-repo-name
      BASE_BRANCH: main

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run agent training script
      run: |
        python -m rl.rl_autopr

    - name: Run Auto PR Generator
      run: |
        echo "$GH_PAT" | gh auth login --with-token
        python main.py

    - name: Add comment to PR
      if: github.event_name == 'pull_request'
      uses: peter-evans/create-or-update-comment@v4
      with:
        token: ${{ secrets.GH_PAT }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ✅ Agent training and PR generation completed successfully!